default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: canteen_reservation_system_development

test:
  <<: *default
  database: canteen_reservation_system_test

production:
  <<: *default
  database: canteen_reservation_system_production
  username: canteen_reservation_system
  password: <%= ENV['CANTEEN_RESERVATION_SYSTEM_DATABASE_PASSWORD'] %>
